# Generated by Django 4.2 on 2026-02-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Destination', models.CharField(max_length=200)),
                ('Landmark_Name', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Image_Url', models.URLField(blank=True, max_length=500)),
            ],
        ),
    ]
