# Generated by Django 4.2 on 2026-04-13 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRecognitionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='favorite',
            name='landmark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_set', to='core.landmark'),
        ),
        migrations.AlterField(
            model_name='story',
            name='landmark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_set', to='core.landmark'),
        ),
    ]
