# Generated by Django 4.2 on 2026-04-14 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_activitylog_delete_searchlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='landmark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.landmark'),
        ),
    ]
